"""Reporting utilities: generate repair report and write logs."""
from datetime import datetime
from .config import logger

def generate_repair_comment(repairs, errors):
    """Generate an ASCII report summarizing repairs and remaining errors.

    Produces a human-readable block that lists repairs performed and any
    remaining validation errors. Intended to be written to the `_repair.log`.

    Args:
        repairs: dict of repair category -> list of messages.
        errors: dict of error category -> list of messages.

    Returns:
        A multi-line string containing the formatted report.
    """
    lines = []
    lines.append("=" * 80)
    lines.append("MICROSOFT PROJECT XML - VALIDATION AND REPAIR REPORT")
    lines.append("=" * 80)
    lines.append(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    lines.append("")

    if repairs:
        lines.append("REPAIRS MADE:")
        lines.append("-" * 80)
        for category, messages in repairs.items():
            lines.append(f"\n{category}: ({len(messages)} repairs)")
            for msg in messages:
                lines.append(f"  * {msg}")
        lines.append("")

    if errors:
        lines.append("REMAINING ERRORS:")
        lines.append("-" * 80)
        for category, messages in errors.items():
            lines.append(f"\n{category}: ({len(messages)} errors)")
            for msg in messages:
                lines.append(f"  ! {msg}")
        lines.append("")

    if not repairs and not errors:
        lines.append("STATUS: No issues found - file is valid!")
    elif not errors:
        lines.append("STATUS: All issues successfully repaired!")
    else:
        lines.append("STATUS: Some issues could not be automatically repaired.")

    lines.append("=" * 80)

    return "\n".join(lines)

def write_repair_log(log_file, comment_text):
    """Write the generated repair comment text to a logfile.

    Args:
        log_file: Path to the log file to write.
        comment_text: Text content to be written (typically generated by
            `generate_repair_comment`).
    """
    logger.info(f"Writing repair report to: {log_file}")
    with open(log_file, 'w', encoding='utf-8') as f:
        f.write(comment_text)
    logger.info(f"Repair log saved to: {log_file}")
